export const Textures = {
  Overlay: {
    Helmet:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAOUlEQVQ4y2NgGN7ARFH0PwiTrXlqnDUYk2UIzIAiDz3yDQBpDjVVpMwbZGtmZ2H+j4yHoAGjgHgAAH9EJrbNZcEOAAAAAElFTkSuQmCC',
    Chestplate:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAEUlEQVQ4EWMYBaNgFIwCKAAABBAAAVYyfTgAAAAASUVORK5CYII=',
    Leggings:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAANUlEQVQ4y2NgGAXDEZgoiv4HYWLFMRRNjbP+X+Sh919RlPc/IXGsBoAUYTMAmzj1vTAKyAMAD6cluRieScUAAAAASUVORK5CYII=',
    Boots:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAVElEQVQ4y2NgGAWjgJrARFH0P4xd5KH3X1GU9z+yHEgMxkeWgyuYGmcNxiCFoaaKGAaAxEByMDUohsBsQNaMrADGR1eDYgBMEYbzkACyGnzqhhgAAJntOuWFWA43AAAAAElFTkSuQmCC',
  },
  Textures: {
    Helmet:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAXklEQVQ4y2NgGJ4gODj4Pwjj4hPUPG3aNAzFxcXF/01NTf8Tpfn8+fMYCkHiBA0BGbB582acBoAwUQaAMLKfQZpAthNtALYAA2mk2ACiwgCXLUQZADMElwEENY9QAADYyG3b80w6vwAAAABJRU5ErkJggg==',
    Chestplate:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAlUlEQVQ4jc2R0QnAIBBDXcpJHMVdXMRBHMmSQko8tT3/KgTUS95dbQi/WCmlbnXkwaG1dqvWugVsPSyiAJVSBgP2uFPPBGABgpEQhrW+BOScHyNHtV05HbwDIMbYIRQYJsB2hof+6W/gUh9Kp6KWQQXwEziuHd8F0HEV4gLYgO5dAHbla3PP8yvAQizsM6yQlVzh03UB3pVjRY93eCIAAAAASUVORK5CYII=',
    Leggings:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAaElEQVQ4T2NgGHQgODj4Py5samr6n6Dm8+fPY+DNmzeDcXFxMX5DkA2AaULG06ZNI84AZA0gTJYBMMUgDHI60QbA2MgKcbEHIaDYCyADQAGFHt8gNjZxDAALcWwGYBPHagAyJiQ+OAAAtsi4pUqS5fUAAAAASUVORK5CYII=',
    Boots:
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAASElEQVQ4y2NgGH4gODj4PwzjE8Op+fz582Bsamr6n5A4yQZs3ryZOAPQFYLEQWJEGYBNIckGTJs2jTwDYIrwyYMMZxgFgwwAAMREe99ZR6oOAAAAAElFTkSuQmCC',
  },
};
